import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers as NextUIProvider } from "@/NextUI/provider";
import { Header } from "@/components/header/Header";
import { Footer } from "@/components/footer/Footer";

import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-main" suppressHydrationWarning>
      <body className={`${inter.className} h-screen`} suppressHydrationWarning>
        <NextUIProvider>
          <Header />
          <main className="h-[calc(100dvh-140px)] overflow-auto">
            {children}
          </main>
          <Footer />
        </NextUIProvider>
      </body>
    </html>
  );
}
